### ISSUE TITLE
Generator broken cause of classes

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-hapi#24]
Core using classes is under npm so now all other trailpack have to implement classes as well

```
Trace: [Error: DefaultController should be a class. It is a regular object]
    at TrailsApp.stop (/Users/jaumard/Downloads/testTrails/node_modules/trails/index.js:70:15)
    at /Users/jaumard/Downloads/testTrails/node_modules/trails/lib/trailpack.js:45:27
    at process._tickDomainCallback (node.js:400:9)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by jaumard** [comment]
Fixed on last version
