### ISSUE TITLE
Validation error on reload with trailpack-autoreload 

### ISSUE THREAD

**Issue by zuker** [trailsjs/trailpack-hapi#62]
```
error: 
 TypeError: config.web: ValidationError: "server" is not allowed
   ...
    at Object.validateWebConfig (trailpack-hapi/lib/validator.js:7:12)
    at Hapi.validate (trailpack-hapi/index.js:27:21)
   ...
```

**Comment by zuker** [comment]
Oops, fixed in v1.0.0-beta-3
