### ISSUE TITLE
Error: Unknown handler: file

### ISSUE THREAD

**Issue by konstantinzolotarev** [trailsjs/trailpack-hapi#68]
Failed after: https://github.com/trailsjs/trailpack-hapi/pull/66

```
error:
 Error: Unknown handler: file
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
    at Object.exports.execute.internals.prerequisites.internals.handler.exports.defaults (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/node_modules/hapi/lib/handler.js:108:14)
    at new module.exports.internals.Route.options (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/node_modules/hapi/lib/route.js:55:37)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._addRoute (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/node_modules/hapi/lib/connection.js:370:19)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._route (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/node_modules/hapi/lib/connection.js:362:18)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin._apply (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/node_modules/hapi/lib/plugin.js:575:14)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin.route (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/node_modules/hapi/lib/plugin.js:545:10)
    at Object.registerRoutes (/Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/lib/server.js:53:12)
    at /Volumes/Repos/Coding/OpenSource/trails/trailpack-hapi/index.js:44:20
    at process._tickDomainCallback (node.js:438:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by weyj4** [comment]
@konstantinzolotarev can we close this issue?

**Comment by konstantinzolotarev** [comment]
@weyj4 yep. now working
